# Generated by Django 5.1.5 on 2025-09-17 19:16

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('sub', 'Subscription')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.handle_image_upload),
        ),
    ]
